name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
        
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Installing package list
        run: apt list --installed    
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install selenium pyvirtualdisplay
        
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        run: python Selenium-Template.py
        
